export const discordLink = "https://discord.gg/u9CcbNsWvt"
export const twitterLink = "https://twitter.com/RavenGroupNFT"
export const instaLink = "https://www.instagram.com/theravengroup.io/?hl=en"
export const openseaLink = "https://opensea.io/collection/theravengroupnft"
export const mediumLink = "https://medium.com/@theravengroupnft"